import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  collection,
  query,
  orderBy,
  limit,
  onSnapshot,
} from "firebase/firestore";

import type { ImageItem } from "../../types/asset.type";
import { db } from "../../firebase/firebase";
import Skeleton from "../../components/ui/Skeleton";

import {
  Sparkles,
  Lock,
  Eye,
  Heart,
  Download,
  UserPlus,
} from "lucide-react";

export default function FeedSection() {
  const navigate = useNavigate();

  const [images, setImages] = useState<ImageItem[]>([]);
  const [loading, setLoading] = useState(true);

  /* ---------------- REAL-TIME FEED ---------------- */
  useEffect(() => {
    const q = query(
      collection(db, "images"),
      orderBy("createdAt", "desc"),
      limit(20)
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...(doc.data() as Omit<ImageItem, "id">),
      }));

      setImages(data);
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  /* ---------------- ACTIONS ---------------- */

  const handleGenerateSimilar = (img: ImageItem) => {
    if (!img.prompt) return;
    navigate(`/ai/generate?prompt=${encodeURIComponent(img.prompt)}`);
  };

  const handleBuy = (img: ImageItem) => {
    navigate(`/buy/${img.id}`);
  };

  const handleOpenImage = (img: ImageItem) => {
    navigate(`/image/${img.id}`);
  };

  const handleDownload = (img: ImageItem) => {
    const src =
      img.imagePath ||
      (img as any).imageUrl ||
      "";

    if (!src) return;

    const a = document.createElement("a");
    a.href = src;
    a.download = "image.png";
    a.click();
  };

  /* ---------------- UI ---------------- */

  return (
    <section className="bg-slate-900 py-16">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">

        {/* HEADER */}
        <div className="mb-10 text-center">
          <h2 className="text-3xl font-bold text-white">
            Discover & Remix AI Creations
          </h2>
          <p className="mt-2 text-sm text-slate-400">
            Real-time designs generated by creators like you
          </p>
        </div>

        {/* LOADING */}
        {loading ? (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <Skeleton key={i} className="h-[260px] rounded-2xl" />
            ))}
          </div>
        ) : images.length === 0 ? (
          <p className="text-center text-slate-400">
            No AI creations yet.
          </p>
        ) : (
          <>
            {/* GRID (ONLY 6 ITEMS) */}
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">

              {images.slice(0, 6).map((img) => {
                const isPremium =
                  typeof img.price === "number" && img.price > 0;

                const imageSrc =
                  img.imagePath ||
                  (img as any).imageUrl ||
                  "/fallback.png";

                return (
                  <div
                    key={img.id}
                    className="relative rounded-2xl overflow-hidden bg-black group cursor-pointer"
                    onClick={() => handleOpenImage(img)}
                  >

                    {/* IMAGE */}
                    <img
                      src={imageSrc}
                      className="w-full h-full object-cover transition duration-500 group-hover:scale-105"
                    />

                    {/* GRADIENT */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent z-10" />

                    {/* PREMIUM */}
                    {isPremium && (
                      <div className="absolute top-2 left-2 z-30">
                        <span className="bg-yellow-400 text-black text-[10px] px-2 py-1 rounded-full font-bold">
                          ₹{img.price}
                        </span>
                      </div>
                    )}

                    {/* FLOATING ICONS */}
                    <div className="absolute top-2 right-2 flex flex-col gap-2 z-30 opacity-100 md:opacity-0 md:group-hover:opacity-100">

                      {/* VIEW */}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleOpenImage(img);
                        }}
                        className="bg-black/60 backdrop-blur p-2 rounded-full"
                      >
                        <Eye size={14} className="text-white" />
                      </button>

                      {/* LIKE */}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          console.log("like clicked");
                        }}
                        className="bg-black/60 backdrop-blur p-2 rounded-full"
                      >
                        <Heart size={14} className="text-white" />
                      </button>

                      {/* DOWNLOAD */}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDownload(img);
                        }}
                        className="bg-black/60 backdrop-blur p-2 rounded-full"
                      >
                        <Download size={14} className="text-white" />
                      </button>

                      {/* FOLLOW */}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          console.log("follow clicked");
                        }}
                        className="bg-white text-black text-[10px] px-2 py-1 rounded-full flex items-center gap-1"
                      >
                        <UserPlus size={12} />
                      </button>
                    </div>

                    {/* CREATOR */}
                    <div className="absolute bottom-2 left-2 flex items-center gap-2 z-30 opacity-100 md:opacity-0 md:group-hover:opacity-100">
                      <img
                        src={
                          img.creatorAvatar ||
                          `https://ui-avatars.com/api/?name=${img.creatorName || "User"}`
                        }
                        className="h-7 w-7 rounded-full border border-white"
                      />
                      <span className="text-xs text-white font-medium">
                        {img.creatorName || "Unknown"}
                      </span>
                    </div>

                    {/* STATS */}
                    <div className="absolute bottom-2 right-2 text-xs text-white z-30 opacity-100 md:opacity-0 md:group-hover:opacity-100">
                      ❤️ {img.likes || 0} · ⬇ {img.downloads || 0}
                    </div>
                  </div>
                );
              })}

            </div>

            {/* VIEW MORE */}
            <div className="mt-10 flex items-center justify-center gap-3">
              <button
                onClick={() => navigate("/explore")}
                className="px-6 py-3 rounded-xl border border-white/20 backdrop-blur text-white font-semibold hover:opacity-90"
              >
                View More
              </button>

              {/* CTA */}
              {!loading && images.length > 0 && (
                <div className="text-center">
                  <button
                    onClick={() => navigate("/subscription")}
                    className="rounded-xl bg-gradient-to-r from-pink-500 to-yellow-400 px-6 py-3 text-sm font-semibold text-black hover:opacity-90"
                  >
                    ✨ Upgrade for Unlimited Access
                  </button>
                </div>
              )}
            </div>
          </>
        )}

      </div>
    </section>
  );
}